{% set name = "spec-kit" %}
{% set version = "0.0.89" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/github/spec-kit/archive/v{{ version }}.tar.gz
  sha256: f1ce6998d9f23fd46c448f54bcd8726c51d8b647ca3f24f74be53082d080f564

build:
  entry_points:
    - specify = specify_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - PYTHONIOENCODING=utf8
    - PYTHONUTF8=1
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - typer
    - rich
    - httpx
    - platformdirs
    - readchar
    - truststore >=0.10.3

test:
  imports:
    - specify_cli
  commands:
    - specify --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Specify CLI, part of GitHub Spec Kit. A tool to bootstrap your projects for Spec-Driven Development (SDD).
  license: MIT
  license_file: LICENSE
  home: https://github.com/github/spec-kit

extra:
  recipe-maintainers:
    - rxm7706
